version: "3.2"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB?}
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}

  nginx:
    image: nginx:latest
    volumes:
      - "./docker/nginx/project.conf:/etc/nginx/conf.d/default.conf"
      - "static:/static/"
    ports:
      - 80:80
    depends_on:
      - back

  back:
    build:
      context: .
      dockerfile: docker/back/Dockerfile
      args:
        DB_NAME: ${POSTGRES_DB?}
        DB_USER: ${POSTGRES_USER?}
        DB_PASSWORD: ${POSTGRES_PASSWORD?}
    volumes:
      - "./src/:/usr/src/app/"
      - "./pytest.ini:/usr/src/pytest.ini"
      - "static:/static/"
    depends_on:
      - db

  redis:
    image: 'redis'
    ports:
      - '6379:6379'

volumes:
  static: