# Generated by Django 2.2.7 on 2019-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.UUIDField(unique=True, verbose_name='SKU')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('barcode', models.CharField(blank=True, max_length=10, verbose_name='Barcode')),
                ('photo_url', models.URLField(blank=True, verbose_name='Photo url')),
                ('price', models.IntegerField(null=True, verbose_name='Price in cents')),
                ('producer', models.CharField(blank=True, max_length=255, verbose_name='Producer')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
