# Generated by Django 2.2.7 on 2019-11-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Producer'),
            preserve_default=False,
        ),
    ]
